# Test.
language: python
python:
  - "2.7"
script:
  - python scripts/json_validator.py


# Deploy.
before_deploy:
  - pip install -r requirements.txt
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: release


# Notify.
notifications:
  email: true
  # slack:
  #   rooms:
  #     - $LIGGAT_SLACK
  #   on_success: always
