language: python
python:
  - "2.7"
before_deploy:
  - pip install -r requirements.txt
script:
  - python test.py
deploy:
  provider: script
  script: "echo 'hello this is a deploy'"
  # on:
  #   branch: release
