language: python
python:
  - "2.7"
script:
  - python test.py
before_deploy:
  - pip install -r requirements.txt
deploy:
  provider: script
  script:
    - echo 'starting deploy'
    - aws s3 sync templates/ s3://$CF_S3_BUCKET --delete --region $AWS_REGION
  # put commit hash into file
  # on:
  #   branch: release
